### PR TITLE
Revert "Save all sections on save"

### PR DESCRIPTION
**Pull request by roidayan**
This reverts commit b8942e621cce317bc941c472bab87eb3bf0646fb.

The save option got broken from this commit.

Signed-off-by: Roi Dayan <roi.dayan@gmail.com>

### CODE REVIEW

**Comment by roidayan** [comment]
sorry about that. didn't check it as should.

**Comment by roidayan** [comment]
the problem is the settings sections and fields pass section is as $page so it emulates like we have multiple pages which force us to use form per tab.
I'll do a different commit that will fix it to have a single page of settings so we'll have single submit for all tabs.

**Comment by tareq1988** [comment]
Ah, I didn't check :/

**Comment by roidayan** [comment]
can you merge? if/wehn i'll have a good solution i'll add pull request.

**Comment by roidayan** [comment]
oh you merged. nm.

**Pull request merged**
